export interface EcosystemProviderInfo {
  id: string;
  name: string;
  category: 'Source & delivery' | 'Data & content' | 'Communication' | 'Commerce' | 'Operations & insights';
  protocol: string;
  badge: string;
  description: string;
  defaultScopes: string[];
  defaultIdentifierPlaceholder: string;
  typicalLatencyMs: number;
  mockPayload: (identifier: string) => Record<string, any>;
  liveActionLabels: {
    testLabel: string;
    actionLabel: string;
  };
  triggerAction: (identifier: string) => Promise<{ success: boolean; message: string; details: any }>;
}

export const ECOSYSTEM_PROVIDERS: Record<string, EcosystemProviderInfo> = {
  // SOURCE + DEPLOYMENT
  GitHub: {
    id: 'github',
    name: 'GitHub',
    category: 'Source & delivery',
    protocol: 'REST / GraphQL / GitHub Apps',
    badge: 'Source + PRs',
    description: 'Pull request workflows, branch isolation, and commit authoring.',
    defaultScopes: ['repo:status', 'contents:write', 'pull_requests:write'],
    defaultIdentifierPlaceholder: 'squargraph/studio-web',
    typicalLatencyMs: 32,
    mockPayload: (id) => ({
      repo: id,
      defaultBranch: 'main',
      openPrCount: 3,
      verifiedHooks: ['push', 'pull_request'],
    }),
    liveActionLabels: {
      testLabel: 'Inspect Repo Branches',
      actionLabel: 'Dispatch Git Pull Request',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Branch and PR automation synchronized with GitHub repo ${id}.`,
      details: { branch: 'patch-content-rev', prNumber: 42, status: 'checks_passing' },
    }),
  },
  GitLab: {
    id: 'gitlab',
    name: 'GitLab',
    category: 'Source & delivery',
    protocol: 'GitLab REST v4 / Merge Requests',
    badge: 'Source + MRs',
    description: 'GitLab Merge Request pipeline, CI/CD runners, and repository mirroring.',
    defaultScopes: ['api', 'read_repository', 'write_repository'],
    defaultIdentifierPlaceholder: 'gitlab-org/squargraph-platform',
    typicalLatencyMs: 38,
    mockPayload: (id) => ({
      project: id,
      pipelineStatus: 'passed',
      defaultBranch: 'main',
      mrApprovalRule: '2-approvers-required',
    }),
    liveActionLabels: {
      testLabel: 'Check GitLab CI Runner',
      actionLabel: 'Create Merge Request',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Dispatched GitLab Merge Request !87 for project ${id}. Pipeline running.`,
      details: { mrId: '!87', pipelineId: 'pipe-94819', runner: 'shared-docker' },
    }),
  },
  Bitbucket: {
    id: 'bitbucket',
    name: 'Bitbucket',
    category: 'Source & delivery',
    protocol: 'Atlassian Bitbucket 2.0 API',
    badge: 'Source + Pipelines',
    description: 'Bitbucket repository synchronization, pull requests, and Jira issue links.',
    defaultScopes: ['repository:write', 'pullrequest:write'],
    defaultIdentifierPlaceholder: 'workspace/squargraph-core',
    typicalLatencyMs: 44,
    mockPayload: (id) => ({
      workspaceRepo: id,
      branchRestrictions: ['require_review_approval'],
      jiraIntegration: 'JIRA-SQR-2026',
    }),
    liveActionLabels: {
      testLabel: 'Verify Branch Permissions',
      actionLabel: 'Submit Bitbucket PR',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Bitbucket PR #19 created in ${id} with linked Jira ticket SQR-2026.`,
      details: { prId: 19, destination: 'main', source: 'feature/editorial-update' },
    }),
  },
  Cloudflare: {
    id: 'cloudflare',
    name: 'Cloudflare',
    category: 'Source & delivery',
    protocol: 'Cloudflare Pages / Workers API',
    badge: 'Edge CDN + Pages',
    description: 'Cloudflare Pages edge deployment, cache purging, and instant rollbacks.',
    defaultScopes: ['pages:write', 'zone:cache_purge', 'dns:read'],
    defaultIdentifierPlaceholder: 'squargraph-pages.pages.dev',
    typicalLatencyMs: 19,
    mockPayload: (id) => ({
      projectName: id,
      edgeNodes: 310,
      activeDeployment: 'd-f938aa10',
      ssl: 'Strict (Full)',
      cacheStatus: 'warm',
    }),
    liveActionLabels: {
      testLabel: 'Purge Edge Cache',
      actionLabel: 'Deploy Pages Preview',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Edge cache purged and staging preview deployed to https://${id}.`,
      details: { deploymentId: 'cf-deploy-7749', propagationTime: '1.2s' },
    }),
  },
  Vercel: {
    id: 'vercel',
    name: 'Vercel',
    category: 'Source & delivery',
    protocol: 'Vercel Platform API v9',
    badge: 'Serverless + Previews',
    description: 'Instant preview deployments, branch aliases, and Edge Function routing.',
    defaultScopes: ['deployments:create', 'projects:read', 'domains:read'],
    defaultIdentifierPlaceholder: 'prj_nexus_front_99',
    typicalLatencyMs: 24,
    mockPayload: (id) => ({
      projectId: id,
      framework: 'Next.js 14 App Router',
      latestDeployment: 'https://nexus-git-preview-squargraph.vercel.app',
      regions: ['iad1', 'sin1', 'fra1'],
    }),
    liveActionLabels: {
      testLabel: 'Query Preview Status',
      actionLabel: 'Build Preview Deployment',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Vercel preview deployment built at https://nexus-git-preview-squargraph.vercel.app.`,
      details: { status: 'READY', duration: '14.2s', environment: 'Preview' },
    }),
  },
  Netlify: {
    id: 'netlify',
    name: 'Netlify',
    category: 'Source & delivery',
    protocol: 'Netlify API v1 / Deploy Hooks',
    badge: 'Jamstack + Forms',
    description: 'Netlify atomic deploys, deploy previews, form processing, and rollbacks.',
    defaultScopes: ['sites:read', 'deploys:write'],
    defaultIdentifierPlaceholder: 'site-squargraph-production',
    typicalLatencyMs: 28,
    mockPayload: (id) => ({
      siteId: id,
      deployLock: false,
      sslCertificate: 'Let\'s Encrypt (Auto-renewed)',
      assetOptimization: 'enabled',
    }),
    liveActionLabels: {
      testLabel: 'Check Netlify Build Lock',
      actionLabel: 'Trigger Netlify Deploy',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Triggered Netlify deploy hook. Preview available in 15 seconds.`,
      details: { deployId: 'net-d-9921', context: 'deploy-preview' },
    }),
  },

  // DATA + CMS
  Supabase: {
    id: 'supabase',
    name: 'Supabase',
    category: 'Data & content',
    protocol: 'PostgreSQL + PostgREST + Realtime',
    badge: 'Postgres DB',
    description: 'Postgres schemas, Row Level Security (RLS), and database content mutation.',
    defaultScopes: ['tenancy:read', 'audit:write', 'rls:enforced'],
    defaultIdentifierPlaceholder: 'db.squargraph-core',
    typicalLatencyMs: 22,
    mockPayload: (id) => ({
      projectRef: id,
      databaseEngine: 'PostgreSQL 16.2',
      rlsPoliciesActive: 14,
      tables: ['sections', 'audit_logs', 'customers'],
    }),
    liveActionLabels: {
      testLabel: 'Scan Database Tables',
      actionLabel: 'Execute Migration Diff',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Database tables scanned. RLS enforced across all public schemas for ${id}.`,
      details: { tablesFound: 4, rowCount: 142, transactionState: 'COMMITTED' },
    }),
  },
  Firebase: {
    id: 'firebase',
    name: 'Firebase',
    category: 'Data & content',
    protocol: 'Firestore REST / Admin SDK',
    badge: 'NoSQL Document DB',
    description: 'Firestore collections, document schemas, security rules, and real-time sync.',
    defaultScopes: ['datastore.read_write', 'firebase.auth'],
    defaultIdentifierPlaceholder: 'squargraph-production-db',
    typicalLatencyMs: 26,
    mockPayload: (id) => ({
      projectId: id,
      database: '(default) multi-region nam5',
      rulesEnforced: true,
      collections: ['pages', 'site_settings', 'leads'],
    }),
    liveActionLabels: {
      testLabel: 'Validate Security Rules',
      actionLabel: 'Sync Firestore Document',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Firestore rules compiled and verified. Document patch staged in ${id}.`,
      details: { collection: 'pages/home', writeResult: '2026-09-16T15:58:00Z' },
    }),
  },
  Sanity: {
    id: 'sanity',
    name: 'Sanity',
    category: 'Data & content',
    protocol: 'Sanity Content Lake / GROQ API',
    badge: 'Structured Headless CMS',
    description: 'Structured content lake, GROQ querying, live drafts, and mutation endpoints.',
    defaultScopes: ['mutate:drafts', 'read:published', 'read:drafts'],
    defaultIdentifierPlaceholder: 'proj_sanity_squar_88',
    typicalLatencyMs: 31,
    mockPayload: (id) => ({
      projectId: id,
      dataset: 'production',
      documentTypes: ['homepage', 'portfolioItem', 'author', 'brandTokens'],
      draftMode: true,
    }),
    liveActionLabels: {
      testLabel: 'Query GROQ Schemas',
      actionLabel: 'Commit Mutation Patch',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Sanity GROQ schema verified. Draft mutation applied to dataset "production".`,
      details: { transactionId: 'tx-sanity-3391', documentId: 'drafts.homepage' },
    }),
  },
  Contentful: {
    id: 'contentful',
    name: 'Contentful',
    category: 'Data & content',
    protocol: 'Content Management API (CMA)',
    badge: 'Enterprise CMS',
    description: 'Contentful spaces, content types, entry editing, and environment branching.',
    defaultScopes: ['content_management_manage', 'space:read'],
    defaultIdentifierPlaceholder: 'space_ctf_squargraph_01',
    typicalLatencyMs: 35,
    mockPayload: (id) => ({
      spaceId: id,
      environment: 'master',
      contentTypesCount: 8,
      locales: ['en-US', 'en-GB', 'de-DE'],
    }),
    liveActionLabels: {
      testLabel: 'Inspect Content Models',
      actionLabel: 'Publish Content Entry',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Contentful space ${id} synchronized. Entry published across 3 locales.`,
      details: { entryId: 'entry-hero-copy', version: 4, status: 'published' },
    }),
  },
  Strapi: {
    id: 'strapi',
    name: 'Strapi',
    category: 'Data & content',
    protocol: 'Strapi v4/v5 REST & GraphQL',
    badge: 'Open-Source Headless CMS',
    description: 'Custom content-types, dynamic zones, role-based API tokens, and localized entries.',
    defaultScopes: ['api:read', 'api:write', 'content-manager:full'],
    defaultIdentifierPlaceholder: 'https://cms.squargraph.com/api',
    typicalLatencyMs: 29,
    mockPayload: (id) => ({
      endpoint: id,
      version: 'Strapi v5.2 Enterprise',
      schemas: ['api::article.article', 'api::global.global', 'api::page.page'],
    }),
    liveActionLabels: {
      testLabel: 'Probe API Token Roles',
      actionLabel: 'Update Single Type',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Strapi API token verified. Single-type "Global Settings" updated at ${id}.`,
      details: { model: 'api::global.global', locale: 'en', publishedAt: new Date().toISOString() },
    }),
  },
  WordPress: {
    id: 'wordpress',
    name: 'WordPress',
    category: 'Data & content',
    protocol: 'WordPress REST API & ACF v3',
    badge: 'WP REST + ACF',
    description: 'WordPress pages, theme options, Advanced Custom Fields (ACF), and menus.',
    defaultScopes: ['edit_posts', 'manage_options', 'edit_theme_options'],
    defaultIdentifierPlaceholder: 'vitawellness.com/wp-json/wp/v2',
    typicalLatencyMs: 40,
    mockPayload: (id) => ({
      restRoot: id,
      wpVersion: '6.7.1',
      acfActive: true,
      detectedEndpoints: ['/wp/v2/pages', '/wp/v2/menus', '/acf/v3/options'],
    }),
    liveActionLabels: {
      testLabel: 'Scan WP & ACF Schemas',
      actionLabel: 'Update Front Page Meta',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `WordPress REST API synchronized. Front page ACF meta updated on ${id}.`,
      details: { postId: 14, fieldsUpdated: ['hero_headline', 'cta_link'], status: 'publish' },
    }),
  },

  // COMMUNICATION
  Twilio: {
    id: 'twilio',
    name: 'Twilio',
    category: 'Communication',
    protocol: 'Twilio REST Programmable SMS / Verify',
    badge: 'SMS + 2FA',
    description: 'SMS approval triggers, 2-factor verification, and mission-critical SMS alerts.',
    defaultScopes: ['sms:send', 'verify:check', 'account:read'],
    defaultIdentifierPlaceholder: 'AC_twilio_squargraph_live_99',
    typicalLatencyMs: 38,
    mockPayload: (id) => ({
      accountSid: id,
      senderPhone: '+1 (555) 019-4820',
      activeMessagingService: 'MG_site_approvals',
      smsDeliveryRate: '99.4%',
    }),
    liveActionLabels: {
      testLabel: 'Check SMS Sender Route',
      actionLabel: 'Dispatch Approval SMS',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Twilio SMS dispatched to verified reviewer phones with approval token.`,
      details: { messageSid: 'SM_789a2b', status: 'sent', recipientCount: 2 },
    }),
  },
  WhatsApp: {
    id: 'whatsapp',
    name: 'WhatsApp',
    category: 'Communication',
    protocol: 'Meta WhatsApp Business Cloud API',
    badge: 'WhatsApp Business',
    description: 'Official WhatsApp Business messaging, template notifications, and approval bots.',
    defaultScopes: ['whatsapp_business_messaging', 'whatsapp_business_management'],
    defaultIdentifierPlaceholder: 'waba_id_89481920491',
    typicalLatencyMs: 45,
    mockPayload: (id) => ({
      wabaId: id,
      verifiedBusinessName: 'SQUARGRAPH Studio Official',
      qualityRating: 'High (Green)',
      templatesApproved: ['change_alert_v1', 'approval_request_v2'],
    }),
    liveActionLabels: {
      testLabel: 'Validate WABA Templates',
      actionLabel: 'Send WhatsApp Alert',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `WhatsApp interactive notification dispatched to workspace channel.`,
      details: { messageId: 'wamid.HBgL491', template: 'approval_request_v2' },
    }),
  },
  Resend: {
    id: 'resend',
    name: 'Resend',
    category: 'Communication',
    protocol: 'Resend Modern Email API / React Email',
    badge: 'Transactional Email',
    description: 'Modern developer-first transactional email with React Email template support.',
    defaultScopes: ['emails:send', 'domains:verify'],
    defaultIdentifierPlaceholder: 're_sqr_prod_token_991',
    typicalLatencyMs: 25,
    mockPayload: (id) => ({
      apiKeyRef: id,
      sendingDomain: 'mail.squargraph.com',
      dkimVerified: true,
      spfVerified: true,
    }),
    liveActionLabels: {
      testLabel: 'Verify DKIM & SPF DNS',
      actionLabel: 'Send Test Deployment Email',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Resend transactional email sent to team with unified diff summary.`,
      details: { emailId: 'email_resend_99182', from: 'updates@squargraph.com' },
    }),
  },
  SendGrid: {
    id: 'sendgrid',
    name: 'SendGrid',
    category: 'Communication',
    protocol: 'Twilio SendGrid v3 Mail Send',
    badge: 'High-Volume Email',
    description: 'Enterprise email delivery, sub-users, dynamic templates, and suppression lists.',
    defaultScopes: ['mail.send', 'templates.read'],
    defaultIdentifierPlaceholder: 'SG.live_key_squargraph_818',
    typicalLatencyMs: 34,
    mockPayload: (id) => ({
      apiKeyId: id,
      dedicatedIp: '168.245.10.4',
      reputationScore: '99.8%',
      templateId: 'd-994819204',
    }),
    liveActionLabels: {
      testLabel: 'Check IP Reputation',
      actionLabel: 'Dispatch Dynamic Template',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `SendGrid dynamic template rendered and sent to workspace admins.`,
      details: { statusCode: 202, xMessageId: 'sg-msg-9921' },
    }),
  },
  Slack: {
    id: 'slack',
    name: 'Slack',
    category: 'Communication',
    protocol: 'Slack Block Kit / Webhooks / OAuth',
    badge: 'Team Chat + Bots',
    description: 'Rich Slack Block Kit notifications, interactive approval buttons, and incident bot.',
    defaultScopes: ['chat:write', 'commands', 'incoming-webhook'],
    defaultIdentifierPlaceholder: '#site-releases-squargraph',
    typicalLatencyMs: 28,
    mockPayload: (id) => ({
      channel: id,
      workspaceName: 'Squargraph Global',
      botUser: 'SiteControlBot',
      blockKitEnabled: true,
    }),
    liveActionLabels: {
      testLabel: 'Post Slack Test Ping',
      actionLabel: 'Post Interactive PR Card',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Slack card with [Approve PR] and [View Diff] posted to ${id}.`,
      details: { channel: id, ts: '1726502280.001900', interactive: true },
    }),
  },

  // COMMERCE
  Razorpay: {
    id: 'razorpay',
    name: 'Razorpay',
    category: 'Commerce',
    protocol: 'Razorpay v1 Payment Links & Orders',
    badge: 'India & Global Payments',
    description: 'UPI, cards, netbanking, payment links, subscriptions, and smart routing.',
    defaultScopes: ['orders:read_write', 'payments:read', 'invoices:create'],
    defaultIdentifierPlaceholder: 'rzp_live_squargraph_001',
    typicalLatencyMs: 33,
    mockPayload: (id) => ({
      merchantId: id,
      supportedCurrencies: ['INR', 'USD', 'EUR', 'GBP'],
      upiIntegration: 'active (auto-collect)',
      settlementStatus: 'T+1 Normal',
    }),
    liveActionLabels: {
      testLabel: 'Verify Webhook Signature',
      actionLabel: 'Generate Dynamic Payment Link',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Razorpay payment link created: https://rzp.io/l/sqr-checkout-2026.`,
      details: { orderId: 'order_RZP9910', amount: 18500, currency: 'INR' },
    }),
  },
  Stripe: {
    id: 'stripe',
    name: 'Stripe',
    category: 'Commerce',
    protocol: 'Stripe API / Payment Intents / Checkout',
    badge: 'Global Commerce',
    description: 'Stripe Checkout sessions, Payment Intents, dynamic pricing tables, and webhooks.',
    defaultScopes: ['checkout.sessions.create', 'prices.read', 'webhook_endpoints.read'],
    defaultIdentifierPlaceholder: 'acct_1N92XkSquargraph',
    typicalLatencyMs: 27,
    mockPayload: (id) => ({
      accountId: id,
      liveMode: true,
      payoutSchedule: 'daily',
      pricingTablesLinked: 3,
      applePay: 'enabled',
    }),
    liveActionLabels: {
      testLabel: 'Sync Product Catalog',
      actionLabel: 'Create Checkout Session',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Stripe checkout session initialized with updated catalog pricing.`,
      details: { sessionId: 'cs_live_99a81b', mode: 'payment', url: 'https://checkout.stripe.com/c/pay/cs_live' },
    }),
  },
  Shopify: {
    id: 'shopify',
    name: 'Shopify',
    category: 'Commerce',
    protocol: 'Shopify Storefront & Admin API 2024-04',
    badge: 'Shopify Storefront',
    description: 'Product variants, pricing metafields, Liquid sections, and checkout parameters.',
    defaultScopes: ['write_products', 'write_themes', 'read_inventory'],
    defaultIdentifierPlaceholder: 'kineticapparel.myshopify.com',
    typicalLatencyMs: 36,
    mockPayload: (id) => ({
      storeDomain: id,
      activeTheme: 'Kinetic 2026 High-Performance v2.4',
      productsIndexed: 142,
      currency: 'USD',
    }),
    liveActionLabels: {
      testLabel: 'Scan Storefront Sections',
      actionLabel: 'Sync Liquid Theme Price',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Shopify theme price metafield updated on ${id}.`,
      details: { sku: 'SKU-AERO-01', price: '$185.00', themeId: 84920491 },
    }),
  },
  WooCommerce: {
    id: 'woocommerce',
    name: 'WooCommerce',
    category: 'Commerce',
    protocol: 'WooCommerce REST API v3',
    badge: 'WordPress Commerce',
    description: 'WooCommerce catalog products, variable prices, coupons, and cart endpoints.',
    defaultScopes: ['read_write_products', 'read_write_orders'],
    defaultIdentifierPlaceholder: 'vitawellness.com/wp-json/wc/v3',
    typicalLatencyMs: 42,
    mockPayload: (id) => ({
      storeEndpoint: id,
      wcVersion: '8.9.2',
      productsCount: 38,
      gatewaysActive: ['Stripe', 'Razorpay', 'COD'],
    }),
    liveActionLabels: {
      testLabel: 'Query WooCommerce Products',
      actionLabel: 'Update Product Price',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `WooCommerce product #482 regular price updated to $120.00 on ${id}.`,
      details: { productId: 482, name: '90-min Wellness Consultation', price: '120.00' },
    }),
  },

  // OPERATIONS + ANALYTICS
  Shiprocket: {
    id: 'shiprocket',
    name: 'Shiprocket',
    category: 'Operations & insights',
    protocol: 'Shiprocket India & Cross-Border Logistics API',
    badge: 'Fulfillment & Logistics',
    description: 'Automated courier assignment, airway bill (AWB) generation, and real-time tracking.',
    defaultScopes: ['orders:create', 'tracking:read', 'couriers:assign'],
    defaultIdentifierPlaceholder: 'shiprocket_merchant_sqr_88',
    typicalLatencyMs: 40,
    mockPayload: (id) => ({
      companyId: id,
      courierPartners: ['BlueDart', 'Delhivery', 'FedEx Express', 'DTDC'],
      averageDeliveryDays: 2.1,
      ndrManagement: 'automated',
    }),
    liveActionLabels: {
      testLabel: 'Check Courier Pincode Serviceability',
      actionLabel: 'Generate Test Tracking Event',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Shiprocket logistics pipeline online. AWB generation verified for 26,000+ pincodes.`,
      details: { awb: 'SR99182740', courier: 'Delhivery Surface', status: 'ready_to_ship' },
    }),
  },
  'Google Analytics': {
    id: 'google-analytics',
    name: 'Google Analytics',
    category: 'Operations & insights',
    protocol: 'Google Analytics 4 Measurement Protocol & Admin API',
    badge: 'GA4 Web Stream',
    description: 'GA4 web data streams, Measurement Protocol telemetry, and enhanced conversions.',
    defaultScopes: ['analytics.readonly', 'analytics.edit'],
    defaultIdentifierPlaceholder: 'G-TRACK99SQR8',
    typicalLatencyMs: 25,
    mockPayload: (id) => ({
      measurementId: id,
      propertyId: 'properties/489104921',
      enhancedMeasurement: true,
      dataRetentionMonths: 14,
    }),
    liveActionLabels: {
      testLabel: 'Verify Tag Placement',
      actionLabel: 'Dispatch Test Telemetry Event',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Google Analytics 4 event "page_view_custom" dispatched with status 204.`,
      details: { streamId: id, validationCode: 'VALID_EVENT', payloadLength: 412 },
    }),
  },
  'Search Console': {
    id: 'search-console',
    name: 'Search Console',
    category: 'Operations & insights',
    protocol: 'Google Search Console URL Inspection API',
    badge: 'SEO & Indexing',
    description: 'URL inspection, real-time Googlebot indexing status, and sitemap validation.',
    defaultScopes: ['webmasters.readonly', 'webmasters'],
    defaultIdentifierPlaceholder: 'sc-domain:squargraph.com',
    typicalLatencyMs: 48,
    mockPayload: (id) => ({
      siteUrl: id,
      permissionLevel: 'siteOwner',
      indexedPages: 84,
      sitemapSubmitted: 'https://squargraph.com/sitemap.xml',
      mobileUsability: 'Passed',
    }),
    liveActionLabels: {
      testLabel: 'Inspect Googlebot Index Status',
      actionLabel: 'Submit Sitemap for Recrawl',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Search Console inspection completed: URL is indexed on Google (Crawl: Googlebot Smartphone).`,
      details: { indexingState: 'INDEXED', coverageResult: 'Submitted and indexed', robotPass: true },
    }),
  },
  'Meta Pixel': {
    id: 'meta-pixel',
    name: 'Meta Pixel',
    category: 'Operations & insights',
    protocol: 'Meta Pixel & Conversions API (CAPI)',
    badge: 'Ad Conversion Tracking',
    description: 'Client pixel script, server-side Conversions API (CAPI), and event deduplication.',
    defaultScopes: ['ads_management', 'business_management'],
    defaultIdentifierPlaceholder: 'pixel_id_948192049102',
    typicalLatencyMs: 31,
    mockPayload: (id) => ({
      pixelId: id,
      capiEnabled: true,
      eventMatchQuality: '8.8 / 10',
      activeEvents: ['PageView', 'ViewContent', 'InitiateCheckout', 'Lead'],
    }),
    liveActionLabels: {
      testLabel: 'Test Event Deduplication',
      actionLabel: 'Send Test Conversion API Event',
    },
    triggerAction: async (id) => ({
      success: true,
      message: `Meta CAPI server-side event "Lead" delivered with match key deduplication.`,
      details: { eventsReceived: 1, fbtraceId: 'E_fb_99a81b', matchQuality: 'High' },
    }),
  },
};
