do $$ declare r record; begin
  for r in select policyname, tablename from pg_policies where schemaname='public' and tablename like 'control_%' loop
    execute format('drop policy if exists %I on public.%I', r.policyname, r.tablename);
  end loop;
end $$;

create policy control_profiles_self_insert on public.control_profiles for insert to authenticated with check (user_id = auth.uid());
create policy control_profiles_self_select on public.control_profiles for select to authenticated using (user_id = auth.uid());
create policy control_profiles_self_update on public.control_profiles for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy control_org_member_select on public.control_organizations for select to authenticated using (control_is_member(id));
create policy control_org_owner_update on public.control_organizations for update to authenticated using (control_has_role(id, array['owner','admin'])) with check (control_has_role(id, array['owner','admin']));
create policy control_membership_member_select on public.control_memberships for select to authenticated using ((user_id = auth.uid()) or control_is_member(organization_id));
create policy control_membership_admin_write on public.control_memberships for all to authenticated using (control_has_role(organization_id, array['owner','admin'])) with check (control_has_role(organization_id, array['owner','admin']));
create policy control_workspace_member_select on public.control_workspaces for select to authenticated using (control_is_member(organization_id));
create policy control_workspace_admin_write on public.control_workspaces for all to authenticated using (control_has_role(organization_id, array['owner','admin'])) with check (control_has_role(organization_id, array['owner','admin']));
create policy control_websites_member_select on public.control_websites for select to authenticated using (exists (select 1 from control_workspaces w where w.id = control_websites.workspace_id and control_is_member(w.organization_id)));
create policy control_websites_editor_write on public.control_websites for all to authenticated using (exists (select 1 from control_workspaces w where w.id = control_websites.workspace_id and control_has_role(w.organization_id, array['owner','admin','editor']))) with check (exists (select 1 from control_workspaces w where w.id = control_websites.workspace_id and control_has_role(w.organization_id, array['owner','admin','editor'])));
create policy control_integrations_member_select on public.control_integrations for select to authenticated using (exists (select 1 from control_workspaces w where w.id = control_integrations.workspace_id and control_is_member(w.organization_id)));
create policy control_integrations_admin_write on public.control_integrations for all to authenticated using (exists (select 1 from control_workspaces w where w.id = control_integrations.workspace_id and control_has_role(w.organization_id, array['owner','admin']))) with check (exists (select 1 from control_workspaces w where w.id = control_integrations.workspace_id and control_has_role(w.organization_id, array['owner','admin'])));
create policy control_provider_connections_member_select on public.control_provider_connections for select to authenticated using (exists (select 1 from control_workspaces w where w.id = control_provider_connections.workspace_id and control_is_member(w.organization_id)));
create policy control_provider_connections_admin_write on public.control_provider_connections for all to authenticated using (exists (select 1 from control_workspaces w where w.id = control_provider_connections.workspace_id and control_has_role(w.organization_id, array['owner','admin']))) with check (exists (select 1 from control_workspaces w where w.id = control_provider_connections.workspace_id and control_has_role(w.organization_id, array['owner','admin'])));
create policy control_jobs_member_select on public.control_jobs for select to authenticated using (exists (select 1 from control_workspaces w where w.id = control_jobs.workspace_id and control_is_member(w.organization_id)));
create policy control_jobs_editor_write on public.control_jobs for all to authenticated using (exists (select 1 from control_workspaces w where w.id = control_jobs.workspace_id and control_has_role(w.organization_id, array['owner','admin','editor']))) with check (exists (select 1 from control_workspaces w where w.id = control_jobs.workspace_id and control_has_role(w.organization_id, array['owner','admin','editor'])));
create policy control_assets_member_select on public.control_assets for select to authenticated using (exists (select 1 from control_workspaces w where w.id = control_assets.workspace_id and control_is_member(w.organization_id)));
create policy control_assets_editor_write on public.control_assets for all to authenticated using (exists (select 1 from control_workspaces w where w.id = control_assets.workspace_id and control_has_role(w.organization_id, array['owner','admin','editor']))) with check (exists (select 1 from control_workspaces w where w.id = control_assets.workspace_id and control_has_role(w.organization_id, array['owner','admin','editor'])));
create policy control_activity_member_select on public.control_activity for select to authenticated using (exists (select 1 from control_workspaces w where w.id = control_activity.workspace_id and control_is_member(w.organization_id)));
create policy control_activity_member_insert on public.control_activity for insert to authenticated with check (exists (select 1 from control_workspaces w where w.id = control_activity.workspace_id and control_is_member(w.organization_id)));
create policy control_subscriptions_member_select on public.control_subscriptions for select to authenticated using (control_is_member(organization_id));
